W6D3-CatAPI/CatAPI/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats do
    # /cats/:cat_id/toys
    #this is up here, because it will be different for each individual cat, so nest it
    #that way we grab the toys for each individual cat based on id in url'
    resources :toys, only: [:index, :new]

    #Note, dotn nest 2 levels deep, like memories for toys, would get weird url /cats/:cat_id/toys/memories  <--makes no sense
    # Would be better to put down below resources in a new do loop.
  end
  # /toys/:id
  #With these ones, we can put the id in the body, instead of the url, instead of seperating
  #Now we can just have a simple url, and include all info in the bdoy
  resources :toys, only: [:show, :update, :create, :destroy] # do
  # resouces :memories, only :index   -------------From example above about memories
  #end

  root to: redirect("/cats")
end

W6D3-CatAPI/CatAPI/app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :skill, presence: true

  has_many :toys
end

W6D3-CatAPI/CatAPI/app/models/toy.rb
class Toy < ApplicationRecord
  TYPES = [
    "string",
    "yarnball",
    "mouse",
  ]
  validates :cat_id, :name, :ttype, presence: true
  validates :ttype, inclusion: TYPES

  belongs_to :cat
end

W6D3-CatAPI/CatAPI/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # This saves us from authenticity token error, take out
  # if actually launching live !!!!!!!!!!!!!!
  skip_before_action :verify_authenticity_token
end

W6D3-CatAPI/CatAPI/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    # GET /cats
    # cats = Cat.all #pull all cats
    # render json: cats #Return in a json format
    #Above made into one line

    #Set and instance variable to access this data from a request in teh view, without @ it would be
    # local variable and not be available in the view
    @cats = Cat.all
    render :index  #This translates to "index.html"
  end

  def show
    # GET /cats/:id
    # cats = Cat.find(params[:id])
    # render json: cats
    # render json: Cat.find(params[:id])
    @cat = Cat.find(params[:id])
    render :show
  end

  #   1. GET request for cat/new form
  #   2. POST to /cats
  #  3. validation fails if i have extra stuff, or not enough
  #   4. Server render the new template again
  # 5. keeps the values filled in from submit, so dont need refill
  #

  # BEFORE THE BELOW HAPPENED
  #   5. Client makes GET request gfor /cats/new
  #   6. client gets a blank form (WE DONT WANT THIS)
  # WE WANT TO SAVE DATA FROM FORM IF IT DOESNT GO THROUGH

  def create
    # POST /cats - create a new cat
    # Content-length: ...
    #
    # {body injson format} = {"cat": {"name": "Sally"}, "dog": { "name": "Bertrand"} }

    @cat = Cat.new(cat_params)

    # NOTE REDIRECT_TO USAGE HERE!
    if @cat.save
      # cat_url(@cat) == /cats/..
      redirect_to cat_url(@cat)
    else
      render :new
      #Old below: V
      #   render json: @cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  #   notes for above.
  #   1. GET  /cats/new to fetch a form
  #   2. User fills out a form, slicks submit
  #   3. POST /cats the data in the form
  #   4. Create action invoked, cat created
  #   5. Send client a reditrect to /cats/#{id}
  #   6. Client makes a GET request for /cats/#{id}
  #   7. Show action for newly created cat is invoked.

  def new
    # show a form to create a new object
    # /cats/new
    @cat = Cat.new
    render :new
  end

  def edit
    #show a form to edit an existing cat
    # @/cats/:id/edit

    @cat = Cat.find(params[:id])

    render :edit
  end

  def update
    # ...
    #Cant shouldnt eb able to update self to become admin...
    @cat = Cat.find(params[:id])
    # if i upload an admin attribute, this tries to set
    # cat.admin, but i dont want this

    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    # ...
    # if !curren_cst_user.admin
    #     raise "error"
    # end

    @cat = Cat.find(params[:id])
    @cat.destroy
    redirect_to cats_url

    # 1. GET /cats
    # 2. click delete button
    # 3. Secnd POST /cats/123; but _method="DELETE" so rails knows
    # to destroy
    # 4. destroys cat. Isuues redirect to client
    # 5. Client GETs /cats again. Without deleted cat
  end

  def cat_params
    params.require(:cat).permit(:name, :skill)
  end
end

W6D3-CatAPI/CatAPI/app/controllers/toys_controller.rb
class ToysController < ApplicationController
  def index
    # /cats/:cat_id/toys
    cat = Cat.find(params[:cat_id])
    render json: cat.toys
  end

  def show
    # /cats/:cat_id/toys/:id
    # prefer to ahve /toys/:id
    render json: Toy.find(params[:id])
  end

  def destroy
    # /toys/:id
    toy = Toy.find(params[:id])
    toy.destroy
    render json: toy
  end

  def update
    # /toys/:id
    toy = Toy.find(params[:id])

    if toy.update(params[:toy].permit(:name))
      render json: toy
    else
      render json: toy.errors.full_messages, status: :unprocessable_entity
    end
  end

  def create
    # POST /toys

    # params => Parameters < HashWIthIndiffferentAccess < Hash
    @toy = Toy.new(toy_params)
    @cat = @toy.cat

    if @toy.save
      redirect_to cat_url(@cat)
    else
      render :new
      #render json: toy.errors.full_messages, status: :unprocessable_entity
    end
  end

  def new
    @cat = Cat.find(params[:cat_id])
    @toy = Toy.new
    render :new
  end

  private

  def toy_params
    params.require(:toy).permit(:cat_id, :name, :ttype)
  end
end

W6D3-CatAPI/CatAPI/app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>
<% form_method = cat.persisted? ? "PATCH" : "POST" %>
<% submit_text = cat.persisted? ? "Update cat!" : "Create cat!" %>


<form action="<%= action_url %>" method="POST">
    <% # Since we can only do GET or post request with method in form, we need to add hidden %> 
    <% # field below to add trhe PATCH %>
    <input type="hidden" name="_method" value="<%= form_method %>">
    
    <label for="cat_name">Name</label>
    <input  type="text" name="cat[name]" 
                        id="cat_name" 
                        value="<%= cat.name %>">
    <br>


    <label for="cat_skill">Skill</label>
    <input type="text" name="cat[skill]" 
                        id="cat_skill"
                        value="<%= cat.skill %>">
    
    <br>

    <input type="text" name="cat[owner][name]">
    <input type="text" name="cat[owner][job_title]">

    <input type="submit" value="<%= submit_text %>">


</form>

W6D3-CatAPI/CatAPI/app/views/cats/edit.html.erb
<h1>Update <%= @cat.name %></h1>
<% # The below line renders a partial, its a piece being rendered inside another templace %>
<% # They always start with an underscore, and we use it to sub out repeatable sections %>
<% # Suuuuuper dry %>
<%= render "form", cat: @cat %>

W6D3-CatAPI/CatAPI/app/views/cats/index.html.erb
<h1>All teh cats!</h1>

<ul>

    <% # ERB is embedded ruby, which we turned this into by adding .erb to file type %>
    <% # We cna use ERB to generate HTML or JSON or whatever wee want %>


    <% # Examples of the ways we can embed ruby commands into the HTML %>
    <li><%= ["this", "is", "so", "cool"].join(", ") %></li>

    <li><%= "Supercool".upcase %></li>

<% # Using a URL helper below %>
    <% @cats.all.each do |cat| %>
    <li>This is the cats name:
        <a href="<%= cat_url(cat) %>"><%= cat.name %></a>
        
        <form action="<%= cat_url(cat) %>" method="POST">
        <% # This hidden request isnt seen, we use it to tell rails about DELETE with _method %>
            <input type="hidden" name="_method" value="DELETE">

            <input type="submit" value="Destroy Cat!">
        </form>
    </li> 
    <% end %>   

    
    <li>DFirst can getre</li>
    <li>Second cat HERE!</li>
</ul>


<a href="<%= new_cat_url %>">Make a new cat!</a>

W6D3-CatAPI/CatAPI/app/views/cats/new.html.erb
<h1>Make a new cat!</h1>

<% # The below line renders a partial, its a piece being rendered inside another templace %>
<% # They always start with an underscore, and we use it to sub out repeatable sections %>
<% # Suuuuuper dry %>
<%= render "form", cat: @cat %>

W6D3-CatAPI/CatAPI/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<pre><%= @cat.to_json %></pre>

<h2>His toys:</h2>    
<ul>
    <% @cat.toys.each do |toy| %>
    <li><%= toy.name %></li>
    <% end %>
</ul>
<ul>    
    <li><a href="<%= new_cat_toy_url(@cat) %>">New Toy</a></li>
    <li><a href="<%= edit_cat_url(@cat) %>">Edit Cat</a></li>
    <li><a href="<%= cats_url %>">Home</a></li>
</ul>