W7D4-CatRental0/CatRental/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :users, only: [:new, :create, :show]

  # A visitor to your site implicitly has their own session (it's stored in their browser),
  # so there's no need to create routes for different sessions. Only new, create, and destroy are needed.
  resources :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

W7D4-CatRental0/CatRental/app/models/user.rb
class User < ApplicationRecord
  #gives me access to @password instance variable
  attr_reader :password

  validates :user_name, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can\'t be blank" }
  validates :session_token, presence: true, uniqueness: true

  #Either checks our @password instance variable on the first input to validate
    # length, or on future request when its pulled from db, it will appear
    # as nil, so will still pass.
  validates :password, length: { minimum:6, allow_nil: true }

  # line below is correct but i still need to add the method
  after_initialize :ensure_session_token

  #before anythign validated, form submitted ect, check for
  # session token
  before_validation :ensure_session_token

  has_many :requests,
      primary_key: :id,
      foreign_key: :user_id,
      class_name: :CatRentalRequest,
      dependent: :destroy

  has_many :cats,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Cat,
    dependent: :destroy

# Will add this in shortly when i create sessions
  # has_many :sessions,
  #     primary_key: :id,
  #     foreign_key: :user_id,
  #     class_name: :session,
  #     dependent: :destroy

    # Use this method in controller to make sure only if a person owns a cat
    # then they are alolowed to approve, or denyt, or edit/update
  def owns_cat?(cat)
    cat.user_id == self.id
  end

  def has_cats?
    # checks if cats array is empty or not to determine
     !self.cats.empty?
  end

  def has_requests?
    # checks if requssts array is empty or not to determine
     !self.requests.empty?
  end

  def has_sessions?
    # checks if sessions array is empty or not to determine
    # Set ar requests atm while i set up sessions
     !self.requests.empty?
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return user if user && user.is_password?(password)
  end


  # Helper methods to make interacting with User object easier.
  # we make @password an instance variable, but never save to db, so we can still
  # validate it above to ensure length.

  # validations do not need to check only database columns; you can apply a validation to any attribute.
  # the password will be around when first signing in, but upod further
  # instances it wont exist

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    #turining our stored string digest back into obj so we can call method to
    #compare to submitted password
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    # Resets our session token and outputs it so we can pass it to our
    #  session[:session_token] when creating a new session on login.
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end


end

W7D4-CatRental0/CatRental/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # Requires no user to be logged in if going to create or new pages
  before_action :require_no_user!, only: [:create, :new]
  before_action :require_user_is_current_user!, only: [:show]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      # login!(@user)
      login_user!(@user)
      redirect_to cats_url
    else
      #  Wil add in error to flash here
      redirect_to new_user_url, flash: { error_message: "Invalid Credentials"}
    end
  end

  def show
    @user = User.find(params[:id])

    unless @user && @user == current_user
      # if invalid user, or not the current user, redirect to index
      redirect_to cats_url
      return
    end
    # if its the current user viewing their own page, render
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:password, :user_name)
  end
end

W7D4-CatRental0/CatRental/app/views/users/new.html.erb
<main class="new-request-main">

  <header class="new-request-header">
    <h1>New User</h1>
  </header>

  <section class="new-request-session">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <form action="<%= users_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

      <label for="user_username">Username</label>
      <input type="text" name="user[user_name]" id="user_username">

      <label for="user_password">Password</label>
      <input type="password" name="user[password]" id="user_password">

      <input class="button" type="submit" value="Create User!">
    </form>
  </section>

</main>

W7D4-CatRental0/CatRental/app/views/users/show.html.erb
<main class="self-main" <%= !current_user.has_cats? && !current_user.has_requests? && !current_user.has_sessions? ? "style=height:85.6vh;" : "" %>>
    <header class="self-header">
      <h2>User Info</h2>
    </header>

    <section class="user-name-section">
        <p><b>Name:</b> <%= current_user.user_name %> <a href="#">edit</a></p>
        <p><b>Pass:</b> <%= current_user.password_digest[0..12] %>....... <a href="#">edit</a></p>
        <p><b>Creation date:</b> <%= current_user.created_at %> </p>
    </section>

  <header class="self-header">
    <h2>Cats:</h2>
  </header>
  <section class="user-cats-section">
      <% if current_user.has_cats? %>
        <% @user.cats.order('name').each do |cat| %>
          <div class="user-cats-display-div">
              <p><a href="<%= cat_url(cat) %>"><%= cat.name %></a></p>
          </div>
        <% end %>
      <% else %>
       <p>You dont have any cats yet!</p>
      <% end %>

  </section>
  <header class="self-header">
    <h2>Rental Requests:</h2>
  </header>
  <section class="user-requests-section">
      <% if current_user.has_requests? %>
        <% @user.requests.includes(:cat).order('start_date').each do |req| %>
        <div class="user-reqeusts-display-div">
            <p>Cat: <%= req.cat.name %></p>
            <p>Start: <%= req.start_date %></p>
            <p>End: <%= req.end_date %></p>
            <p>Approved? <%= req.approved? ? "Yes" : "No" %></p>
            <p><a class="button" href="<%= cat_url(req.cat) %>">View</a></p>
          </div>
        <% end %>
      <% else %>
       <p>You dont have any rental requests yet!</p>
      <% end %>
  </section>
  <header class="self-header">
    <h2>Current Sessions:</h2>
  </header>
  <section class="user-sessions-section">

      <% if current_user.has_sessions? %>

          <div class="user-sessions-display-div">
              <p>Session: </p> <p><%= @user.session_token[0..8] %></p>
              <p>Session Location: </p> <p>40.771,-74.044</p>
              <p><a class="button" href="#">Terminate Session</a></p>
          </div>
          <div class="user-sessions-display-div">
              <p>Session: </p> <p><%= @user.session_token[0..8] %></p>
              <p>Session Location: </p> <p>40.771,-74.044</p>
              <p><a class="button" href="#">Terminate Session</a></p>
          </div>

      <% else %>
        <!-- Should never encounter this, just putting in for testing sake -->
       <p>You dont have any active sessisons yet!</p>
      <% end %>
  </section>
</main>