W9D1-Cat-Rental1/CatRental/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :users, only: [:new, :create, :show]

  # A visitor to your site implicitly has their own session (it's stored in their browser),
  # so there's no need to create routes for different sessions. Only new, create, and destroy are needed.
  resources :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

W9D1-Cat-Rental1/CatRental/app/models/cat.rb
require "action_view"

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  SEXES = [
    "M",
    "F",
  ].freeze

  COLORS = [
    "Black",
    "Brown",
    "White",
    "Grey",
    "Mixed",
  ].freeze

  validates :name, presence: true
  validates :birth_date, presence: true
  validates :color, presence: true
  validates :sex, presence: true
  validates :sex, inclusion: SEXES
  validates :color, inclusion: COLORS
  validates :owner, presence: true

  validate :birth_in_past, if: -> { birth_date }

  has_many :rental_requests,
           primary_key: :id,
           foreign_key: :cat_id,
           class_name: :CatRentalRequest,
           dependent: :destroy

  belongs_to :owner,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  def age
    time_ago_in_words(birth_date)
  end

  private

  def birth_in_past
    if birth_date && birth_date > Time.now
      errors[:birth_date] << "cant be in the future!"
    end
  end
end

W9D1-Cat-Rental1/CatRental/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    #Requires user to be logged in if going to create or edit pages
    # Note we also protect from POST request attacj on create
    # edit is the easiest and just UI related to protect.
    before_action :require_user!, only: [:new, :edit, :create, :update]
    before_action :require_owns_cat!, only: [:edit, :update]

  def index
    @cats = Cat.all

    render :index
  end

  def show
    @cat = Cat.find(params[:id])

    unless @cat
      # return user to inmdex page if not found
      redirect_to cats_url
      return
    end

    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    #Instead of using a hidden form field on the cat creation or edit pages
    # we use the current user here to update id.
    # if we did the form, or got user input, we would be vulnerable to attack
    # this way we know that since a user must be loggedf in to see _form
    # we can count on current user to be who we want to set teh cat to.
    # <input name="cat[user_id]" type="hidden" value="<%= current_user.id %>"> <<-- Vulnerable to somone inspecting and changing value
    @cat.user_id = current_user.id

    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:error_message] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat  = Cat.find(params[:id])
    unless @cat
      # return user to inmdex page if not found
      redirect_to cats_url
      return
    end

    render :edit
  end

  def update
    @cat = Cat.find(params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:error_message] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def require_owns_cat!
    redirect_to cat_url(current_cat) unless current_user.owns_cat?(current_cat)
  end

  def current_cat
    Cat.find(params[:id])
  end

  def cat_params
    params.require(:cat).permit(:name,:birth_date,:sex,:color,:description)
  end
end

W9D1-Cat-Rental1/CatRental/app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = cat_url(cat) %>
  <% button_text = "Update Cat!" %>
  <% header_text = "Edit cat" %>
<% else %>
  <% action_url = cats_url %>
  <% button_text = "Make Cat!" %>
  <% header_text = "Create a new cat" %>
<% end %>

<main class="new-request-main">
    <header class="new-request-header">
      <h2><%= header_text %></h2>
    </header>

    <section class="new-request-section">
      <form action="<%=action_url  %>" method="post">

        <% if cat.persisted? %>
        <input type="hidden" name="_method" value="PATCH">
        <h2> <%= @cat.name %> </h2>
        <% end %>

        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg.first, class: name %>
        <% end %>

        <br>

        <label for="name">Name:</label>
        <input id="name" type="text" name="cat[name]" value="<%=cat.name%>">

        <br>

        <label for="cat_birth_date">Birth Date:</label>
        <input id="cat_birth_date" type="date" name="cat[birth_date]" value="<%=cat.birth_date%>">

        <br>

        <label for="color">Color:</label>
        <select class="" id="color" name="cat[color]">
          <option value="none">--Select Color--</option>
          <% Cat::COLORS.each do |color| %>
          <% selected = cat.color == color %>
          <option value="<%=color%>" <%= selected ? "selected" : "" %> ><%=color%></option>
          <% end %>
        </select>

        <br>

        <label class="sex-label" for="sex">Sex:</label>
        <input id="cat_sex_male" type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
        <label for="cat_sex_male">M</label>
        <input id="cat_sex_female" type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>>
        <label for="cat_sex_female">F</label>

        <br>

        <label for="description">Description:</label>
        <textarea name="cat[description]" placeholder="A brief description of your cat..."><%=cat.description%></textarea>
        <br>

        <input class="button" type="submit" value="<%= button_text %>">
      </form>

  </section>
</main>

W9D1-Cat-Rental1/CatRental/app/views/cats/edit.html.erb
<%= render "form", cat: @cat, action: "PATCH" %>

W9D1-Cat-Rental1/CatRental/app/views/cats/index.html.erb
<main class="index-main">
    <header class="index-header">
      <h2 class="header-text" >Our entire selection of cats:</h2>
      <div class="head-div">
      <a class="button" href=" <%= new_cat_url %> ">New Cat</a>
      <a class="button" href=" <%= new_cat_rental_request_url %>">Rental Request</a>
    </div>
    </header>

    <section class="index-section">

          <% @cats.each do |cat| %>
          <div  class="index-box">
            <div class="index-cat-div">
              <img class="index-cat-pic" src="https://placekitten.com/200/287" alt="cats personal photo">
              <h4><%=cat.name%></h4>
              <a href="<%=cat_url(cat.id)%>">About me</a>
            </div>
          </div>
          <% end %>


    </section>
</main>

W9D1-Cat-Rental1/CatRental/app/views/cats/new.html.erb
<%= render "form", cat: @cat, action: "post"%>

W9D1-Cat-Rental1/CatRental/app/views/cats/show.html.erb
<main class="self-main">
    <header class="self-header">
      <h2>About Me</h2>
      <div class="head-div">
        <!-- Hides the edit button if you dont own the cat -->
        <!-- NOTE: Need to protect more than here, Controller filters to protect from malicious users -->
        <% if current_user && current_user.owns_cat?(current_cat)%>
          <a class="button" href="<%= edit_cat_url %> ">Edit Cat</a>
        <% end %>
        <a class="button" href=" <%= cats_url %> ">All Cats</a>
      </div>
    </header>

    <section class="self-section">
      <div class="self-cat-div">
        <img class="self-cat-pic" src="https://placekitten.com/200/287" alt="cats personal photo">
        <h2><%= @cat.name %></h2>
        <table class="cat-stats">
          <thead>
            <tr>
              <th colspan="1">Attribute</th>
              <th colspan="1">Value</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Age:</td>
              <td><%= @cat.age %></td>
            </tr>
            <tr>
              <td>Color:</td>
              <td><%= @cat.color %></td>
            </tr>
            <tr>
              <td>Sex:</td>
              <td><%= @cat.sex %></td>
            </tr>
            <tr>
              <td>Description:</td>
              <td><%= @cat.description %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </section>

    <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
    <% end %>

  <section class="self-section">
    <header>
      <h2>Rental Requests</h2>
    </header>
    <table class="cat-rental">
      <thead>
        <tr>
          <th colspan="1">Renter:</th>
          <th class="start_header" colspan="1">Start Date:</th>
          <th class="end_header" colspan="1">End Date: </th>
          <th colspan="1">Status: </th>
          <% if current_user && current_user.owns_cat?(current_cat) %>
            <th colspan="1">Action:</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <!-- Using includes on this line allows us to eager load in requesters so  -->
        <!-- we avoid an n+1 quey for pulling in his name each time. We will eager load it Instead -->
        <!--  of default lazy load -->
        <% @cat.rental_requests.includes(:requester).order('start_date').each do |request| %>
        <tr>
          <td><%= request.requester.user_name %></td>
          <td class="start_data"><%= request.start_date %></td>
          <td class="end_data"><%= request.end_date %></td>
          <td><%= request.status %> </td>
          <% if request.pending? && current_user && current_user.owns_cat?(current_cat) %>
              <td class="action-td">
                <form action="<%=approve_cat_rental_request_url(request)%>" method="post">
                  <input class="button" type="submit" name="approve" value="Approve">
                </form>
                <form action="<%=deny_cat_rental_request_url(request)%>" method="post">
                  <input class="button" type="submit" name="deny" value="Deny">
                </form>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div>
        <!-- Able to pass params into query string to carry cat into request form w help from controllers
              and my CatRentalRequest.new(cat_id: params[:cat_id]) creation when called new-->
        <a href=" <%= new_cat_rental_request_url(cat_id: @cat.id) %>" value="cat[<%= params[:id] %>]">New Rental Request</a>
      </div>

  </section>
</main>