W9D1-Cat-Rental1/CatRental/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :cats, only: [:index, :show, :new, :create, :edit, :update]

  resources :cat_rental_requests, only: [:new, :create] do
    member do
      post 'approve'
      post 'deny'
    end
  end

  resources :users, only: [:new, :create, :show]

  # A visitor to your site implicitly has their own session (it's stored in their browser),
  # so there's no need to create routes for different sessions. Only new, create, and destroy are needed.
  resources :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

W9D1-Cat-Rental1/CatRental/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatRental</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
  </head>

  <body>
    <header class="main-header">
      <h1 class="main-title"><a href="<%= cats_url %>">Catz4Rent</a></h1>
      <div class="head-div">
        <!-- edit what is displayed in header based on if logged in or not -->
        <% if !current_user.nil? %>
          <p class="welcome_message">Welcome</p>
          <a class="user_link" href="<%= user_url(current_user.id) %>"><%= current_user.user_name %> </a>

          <form action="<%= session_url(session.id) %>" method="post">
            <input type="hidden" name="_method" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="DELETE">

            <input class="logout_input" type="submit" value="Logout">
          </form>

        <% else %>
          <a class="button" href="<%= new_session_url %>">Sign In</a>
          <a class="button" href="<%= new_user_url %>">Sing Up</a>
        <% end %>
      </div>
    </header>

    <%= yield %>
  </body>
</html>